ansible_lint:
  mock_modules:
    - win_domain_group
    - win_domain_user
github_actions:
  periodic_ci:
    schedule:
      - cron: "0 2 * * 6"
runtime_collection_requirements:
  - name: ansible.posix
  - name: community.general
  - name: fedora.linux_system_roles
test_collection_requirements:
  - name: ansible.windows
  - name: community.windows
  - name: microsoft.ad
