github_actions:
  periodic_ci:
    schedule:
      - cron: "0 7 * * 6"
runtime_collection_requirements:
  - name: ansible.posix
  - name: community.general
  - name: fedora.linux_system_roles
test_collection_requirements: []
