github_actions:
  weekly_ci:
    schedule:
      - cron: "0 10 * * 6"
ansible_lint:
  skip_list:
    - galaxy[no-changelog]  # vendor
  mock_roles:
    - performancecopilot.metrics.bpftrace
    - performancecopilot.metrics.elasticsearch
    - performancecopilot.metrics.grafana
    - performancecopilot.metrics.mssql
    - performancecopilot.metrics.pcp
    - performancecopilot.metrics.postfix
    - performancecopilot.metrics.redis
    - performancecopilot.metrics.repository
    - performancecopilot.metrics.spark
