github_actions:
  periodic_ci:
    schedule:
      - cron: "0 21 * * 6"
tmt_hardware:
  memory: ">= 4096 MB"
runtime_collection_requirements:
  - name: fedora.linux_system_roles
test_collection_requirements:
  - name: ansible.windows
  - name: fedora.linux_system_roles
