github_actions:
  periodic_ci:
    schedule:
      - cron: "0 5 * * 0"
runtime_collection_requirements:
  - name: ansible.posix
  - name: community.general
test_collection_requirements:
  - name: fedora.linux_system_roles
