github_actions:
  periodic_ci:
    schedule:
      - cron: "0 6 * * 0"
  codeql:
    schedule:
      - cron: "37 4 * * 4"
ansible_lint:
  mock_modules:
    - seboolean
    - selinux
runtime_collection_requirements:
  - name: ansible.posix
  - name: community.general
  - name: fedora.linux_system_roles
test_collection_requirements: []
