github_actions:
  periodic_ci:
    schedule:
      - cron: "0 7 * * 0"
  codeql:
    schedule:
      - cron: "8 10 * * 3"
runtime_collection_requirements:
  - name: ansible.posix
test_collection_requirements:
  - name: fedora.linux_system_roles
