github_actions:
  periodic_ci:
    schedule:
      - cron: "0 9 * * 0"
role_specific_contributing: include_files/ssh_contributing.md
runtime_collection_requirements:
  - name: ansible.posix
  - name: community.general
test_collection_requirements: []
