github_actions:
  weekly_ci:
    schedule:
      - cron: "30 23 * * 6"
  codeql:
    schedule:
      - cron: "34 3 * * 2"
runtime_collection_requirements:
  - name: ansible.posix
    version: "{{ ansible_posix_version }}"
  - name: fedora.linux_system_roles
test_collection_requirements: []
