github_actions:
  periodic_ci:
    schedule:
      - cron: "0 17 * * 0"
  codeql:
    schedule:
      - cron: "4 3 * * 2"
runtime_collection_requirements:
  - name: ansible.posix
test_collection_requirements: []
