---
name: Ansible Lint
on:  # yamllint disable-line rule:truthy
  pull_request:
  merge_group:
    branches:
      - main
    types:
      - checks_requested
  push:
    branches:
      - main
  workflow_dispatch:
env:
  LSR_ROLE2COLL_NAMESPACE: {{ lsr_namespace }}
  LSR_ROLE2COLL_NAME: {{ lsr_name }}
permissions:
  contents: read
jobs:
  ansible_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Update pip, git
        run: |
          set -euxo pipefail
          sudo apt update
          sudo apt install -y git

      - name: Checkout repo
        uses: {{ gha_checkout_action }}

      - name: Install tox, tox-lsr
        run: |
          set -euxo pipefail
          pip3 install "{{ tox_lsr_url }}"

      - name: Convert role to collection format
        run: |
          set -euxo pipefail
          TOXENV=collection lsr_ci_runtox
          coll_dir=".tox/ansible_collections/$LSR_ROLE2COLL_NAMESPACE/$LSR_ROLE2COLL_NAME"
          # ansible-lint action requires a .git directory???
          # https://github.com/ansible/ansible-lint/blob/main/action.yml#L45
          mkdir -p "$coll_dir/.git"

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24
        with:
{%- raw %}
          working_directory: ${{ github.workspace }}/.tox/ansible_collections/${{ env.LSR_ROLE2COLL_NAMESPACE }}/${{ env.LSR_ROLE2COLL_NAME }}
{%- endraw +%}
