# Codespell configuration is within .codespellrc
---
name: Codespell
on:  # yamllint disable-line rule:truthy
  - pull_request
permissions:
  contents: read
jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: {{ gha_checkout_action }}

      - name: Codespell
        uses: codespell-project/actions-codespell@v2
