---
# yamllint disable rule:line-length
name: MarkDown Lint
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Update pip, git
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y git
      - name: Check out code
        uses: {{ gha_checkout_action }}
      - name: Run markdownlint
        uses: actionshub/markdownlint@main
